name: e2e tests

on: deployment_status

jobs:
  e2etest:
    name: End-to-end tests # this job will be trigerred only in case of successful website deployment
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}