name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Build and deploy 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify
        env:
          HUGO_ENV: ${{ secrets.HUGO_ENV }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
        env:
          HUGO_ENV: ${{ secrets.HUGO_ENV }}

      - name: Sleep for 1 min # Wait for the deployment to be completed before running Cypress tests
        if: github.ref == 'refs/heads/master'
        run: sleep 60
  
  e2etest:
    name: End-to-end tests # this job will be trigerred only in case of successful website deployment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}